function ExportButtons({ reports = [] }) {
  // =========================
  // EXPORT CSV
  // =========================
  const exportCSV = () => {
    if (reports.length === 0) {
      alert("No reports available to export.");
      return;
    }

    const headers = [
      "Report Name",
      "Type",
      "Generated By",
      "Resources",
      "Threats",
      "Security Score",
      "Status",
      "Created",
    ];

    const rows = reports.map((report) => [
      report.reportName,
      report.reportType,
      report.generatedBy,
      report.totalResources,
      report.totalThreats,
      `${report.securityScore}%`,
      report.status,
      new Date(report.createdAt).toLocaleString(),
    ]);

    const csvContent = [
      headers.join(","),
      ...rows.map((row) =>
        row
          .map((value) =>
            `"${String(value).replace(/"/g, '""')}"`
          )
          .join(",")
      ),
    ].join("\n");

    const blob = new Blob([csvContent], {
      type: "text/csv;charset=utf-8;",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = "cloudsentinel-security-reports.csv";

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  // =========================
  // DOWNLOAD PDF
  // =========================
  const downloadPDF = () => {
    if (reports.length === 0) {
      alert("No reports available to download.");
      return;
    }

    window.print();
  };

  return (
    <div className="flex flex-wrap gap-3">
      <button
        onClick={downloadPDF}
        className="rounded-xl bg-cyan-500 px-6 py-3 font-semibold text-slate-950 transition hover:bg-cyan-400"
      >
        Download PDF
      </button>

      <button
        onClick={exportCSV}
        className="rounded-xl bg-green-500 px-6 py-3 font-semibold text-white transition hover:bg-green-400"
      >
        Export CSV
      </button>
    </div>
  );
}

export default ExportButtons;