function ReportTable({ reports = [] }) {
  return (
    <div className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900">

      <table className="min-w-full">

        <thead className="bg-slate-950">
          <tr>

            <th className="p-4 text-left text-sm text-slate-300">
              Report Name
            </th>

            <th className="p-4 text-left text-sm text-slate-300">
              Type
            </th>

            <th className="p-4 text-left text-sm text-slate-300">
              Generated By
            </th>

            <th className="p-4 text-left text-sm text-slate-300">
              Resources
            </th>

            <th className="p-4 text-left text-sm text-slate-300">
              Threats
            </th>

            <th className="p-4 text-left text-sm text-slate-300">
              Security Score
            </th>

            <th className="p-4 text-left text-sm text-slate-300">
              Status
            </th>

            <th className="p-4 text-left text-sm text-slate-300">
              Created
            </th>

          </tr>
        </thead>

        <tbody>

          {reports.length === 0 ? (

            <tr>
              <td
                colSpan="8"
                className="p-10 text-center text-slate-400"
              >
                No reports available.
              </td>
            </tr>

          ) : (

            reports.map((report) => (

              <tr
                key={report._id}
                className="border-t border-slate-800 transition hover:bg-slate-800/40"
              >

                <td className="p-4 font-semibold text-white">
                  {report.reportName}
                </td>

                <td className="p-4 text-cyan-400">
                  {report.reportType}
                </td>

                <td className="p-4 text-slate-300">
                  {report.generatedBy}
                </td>

                <td className="p-4 font-semibold text-green-400">
                  {report.totalResources}
                </td>

                <td className="p-4 font-semibold text-red-400">
                  {report.totalThreats}
                </td>

                <td className="p-4">

                  <span
                    className={`font-semibold ${
                      report.securityScore >= 90
                        ? "text-green-400"
                        : report.securityScore >= 75
                        ? "text-yellow-400"
                        : "text-red-400"
                    }`}
                  >
                    {report.securityScore}%
                  </span>

                </td>

                <td className="p-4">

                  <span
                    className={`rounded-full px-3 py-1 text-xs font-semibold ${
                      report.status === "Generated"
                        ? "bg-green-500/10 text-green-400"
                        : report.status === "Completed"
                        ? "bg-cyan-500/10 text-cyan-400"
                        : "bg-yellow-500/10 text-yellow-400"
                    }`}
                  >
                    {report.status}
                  </span>

                </td>

                <td className="p-4 text-sm text-slate-400">
                  {report.createdAt
                    ? new Date(
                        report.createdAt
                      ).toLocaleString()
                    : "-"}
                </td>

              </tr>

            ))

          )}

        </tbody>

      </table>

    </div>
  );
}

export default ReportTable;